import type { Metadata } from "next";
import { Nunito, Fredoka } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/react";
import Script from "next/script";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";
import InstallPrompt from "@/components/InstallPrompt";

// Kid-friendly body font — rounded, extra-legible, loaded via CSS variable
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
  weight: ["400", "600", "700", "800", "900"],
});

// Display font for headings and big playful labels
const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const siteUrl = "https://www.jiggyjoy.com";

const defaultTitle = "Free Kids Games, Coloring Pages & Worksheets | JiggyJoy";
const defaultDescription =
  "Free online games, coloring pages and printable worksheets for kids. No signup, no download — 100% free and works on any device.";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: defaultTitle,
    template: "%s | JiggyJoy",
  },
  description: defaultDescription,
  keywords: [
    "free kids games",
    "coloring pages for kids",
    "educational games for kids",
    "printable worksheets",
    "free printable coloring pages",
    "math games for kids",
    "online learning games",
    "kids activities",
    "toddler games",
    "free educational resources",
    "alphabet games",
    "kids coloring sheets",
  ],
  openGraph: {
    siteName: "JiggyJoy",
    type: "website",
    url: siteUrl,
    title: defaultTitle,
    description: defaultDescription,
    // image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: defaultTitle,
    description: defaultDescription,
    // image auto-generated by app/opengraph-image.tsx
  },
  alternates: {
    canonical: "/",
  },
  verification: {
    google: "yPFsdm56U4bCUf8Y1iOWUXU6HPVn25Z7t1sLV2nH9dY",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`h-full ${nunito.variable} ${fredoka.variable}`}
    >
      <body className="min-h-full flex flex-col antialiased font-sans">
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
        <Analytics />
        <ServiceWorkerRegister />
        <InstallPrompt />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-6XN1W2RTC1"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-6XN1W2RTC1');
          `}
        </Script>
      </body>
    </html>
  );
}
