import type { Metadata } from "next";
import { Nunito, Fredoka } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FooterGate from "@/components/FooterGate";
import { Analytics } from "@vercel/analytics/react";
import Script from "next/script";
import ClientSideAddons from "@/components/ClientSideAddons";
import { JsonLd, organizationSchema, websiteSchema } from "@/lib/schemas";

// Kid-friendly body font — rounded, extra-legible, loaded via CSS variable
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
  weight: ["400", "600", "700", "800", "900"],
});

// Display font for headings and big playful labels
const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const siteUrl = "https://www.jiggyjoy.com";

const defaultTitle = "Free Kids Games, Coloring Pages & Worksheets | JiggyJoy";
const defaultDescription =
  "Free online games, coloring pages and printable worksheets for kids. No signup, no download — 100% free and works on any device.";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: defaultTitle,
    template: "%s | JiggyJoy",
  },
  description: defaultDescription,
  keywords: [
    "free kids games",
    "coloring pages for kids",
    "educational games for kids",
    "printable worksheets",
    "free printable coloring pages",
    "math games for kids",
    "online learning games",
    "kids activities",
    "toddler games",
    "free educational resources",
    "alphabet games",
    "kids coloring sheets",
  ],
  openGraph: {
    siteName: "JiggyJoy",
    type: "website",
    url: siteUrl,
    title: defaultTitle,
    description: defaultDescription,
    // image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: defaultTitle,
    description: defaultDescription,
    // image auto-generated by app/opengraph-image.tsx
  },
  alternates: {
    canonical: "/",
  },
  verification: {
    google: "yPFsdm56U4bCUf8Y1iOWUXU6HPVn25Z7t1sLV2nH9dY",
    // TODO: Paste the Bing Webmaster Tools verification code after signing up at
    // https://www.bing.com/webmasters (one-click import from GSC).
    // other: { "msvalidate.01": "YOUR-BING-CODE-HERE" },
    // TODO: Paste the Pinterest domain verification code after creating a free
    // business account at https://www.pinterest.com/business/create/ and
    // claiming the jiggyjoy.com domain.
    // other: { "p:domain_verify": "YOUR-PINTEREST-CODE-HERE" },
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`h-full ${nunito.variable} ${fredoka.variable}`}
    >
      <head>
        {/* Give the browser a head-start on third-party origins so the
            TLS + DNS handshake happens in parallel with HTML parsing
            instead of blocking the first analytics call later on. */}
        <link rel="preconnect" href="https://www.googletagmanager.com" crossOrigin="" />
        <link rel="dns-prefetch" href="https://www.google-analytics.com" />
        <link rel="dns-prefetch" href="https://vitals.vercel-insights.com" />
      </head>
      <body className="min-h-full flex flex-col antialiased font-sans">
        <Navbar />
        <main className="flex-1">{children}</main>
        {/* Footer is a pure server component. FooterGate is a tiny client
            shim that hides it on individual game pages — everything inside
            stays RSC-rendered and out of the page JS bundle. */}
        <FooterGate>
          <Footer />
        </FooterGate>
        {/* Site-wide structured data — tells Google and AI crawlers who we
            are and enables sitelinks search box in SERPs. */}
        <JsonLd data={organizationSchema()} />
        <JsonLd data={websiteSchema()} />
        <Analytics />
        {/* Non-critical client addons (SW register + PWA install banner)
            are code-split and loaded after the main document is ready. */}
        <ClientSideAddons />
        {/* Google Analytics — lazyOnload keeps gtag.js completely off the
            critical path. It loads during browser idle, well after LCP. */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-6XN1W2RTC1"
          strategy="lazyOnload"
        />
        <Script id="google-analytics" strategy="lazyOnload">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-6XN1W2RTC1');
          `}
        </Script>
      </body>
    </html>
  );
}
