import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/react";

const siteUrl = "https://www.jiggyjoy.com";

const defaultTitle = "Free Kids Games, Coloring Pages & Worksheets | JiggyJoy";
const defaultDescription =
  "Free online games, coloring pages and printable worksheets for kids. No signup, no download — 100% free and works on any device.";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: defaultTitle,
    template: "%s | JiggyJoy",
  },
  description: defaultDescription,
  keywords: [
    "free kids games",
    "coloring pages for kids",
    "educational games for kids",
    "printable worksheets",
    "free printable coloring pages",
    "math games for kids",
    "online learning games",
    "kids activities",
    "toddler games",
    "free educational resources",
    "alphabet games",
    "kids coloring sheets",
  ],
  openGraph: {
    siteName: "JiggyJoy",
    type: "website",
    url: siteUrl,
    title: defaultTitle,
    description: defaultDescription,
    // image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: defaultTitle,
    description: defaultDescription,
    // image auto-generated by app/opengraph-image.tsx
  },
  alternates: {
    canonical: "/",
  },
  verification: {
    google: "uukurDQ7I5SSiy7CF4oX4q36LDledZ22PB1qWkASFl0",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-full flex flex-col antialiased">
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
