/**
 * Bulk image data — reads manifest.json generated by scripts/download-bulk.mjs
 * Cached in memory so the file is only read once per server process.
 */

import fs from "fs";
import path from "path";

export type BulkPage = {
  id: string;
  slug: string;
  title: string;
  filename: string;
  tags: string[];
  category: string;
  source: string;
};

export type BulkCategory = {
  slug: string;
  title: string;
  icon: string;
  color: string;
  count: number;
};

const MANIFEST_PATH = path.join(process.cwd(), "public/images/coloring/manifest.json");

// ─── Category display config ───────────────────────────────────────────────────

const BULK_CATEGORY_META: Record<string, { title: string; icon: string; color: string }> = {
  animals:     { title: "Animal Coloring Pages",     icon: "🐾", color: "bg-green-50"   },
  mandalas:    { title: "Mandala Coloring Pages",    icon: "🔮", color: "bg-amber-50"   },
  holidays:    { title: "Holiday Coloring Pages",    icon: "🎉", color: "bg-red-50"     },
  fantasy:     { title: "Fantasy Coloring Pages",    icon: "🧚", color: "bg-purple-50"  },
  nature:      { title: "Nature Coloring Pages",     icon: "🌿", color: "bg-emerald-50" },
  educational: { title: "Educational Coloring Pages",icon: "📚", color: "bg-blue-50"   },
  vehicles:    { title: "Vehicle Coloring Pages",    icon: "🚗", color: "bg-sky-50"     },
  characters:  { title: "Character Coloring Pages",  icon: "🦸", color: "bg-rose-50"   },
  general:     { title: "Coloring Pages",            icon: "🎨", color: "bg-gray-50"   },
};

// ─── Cache ────────────────────────────────────────────────────────────────────

let _cache: BulkPage[] | null = null;

export function loadManifest(): BulkPage[] {
  if (_cache !== null) return _cache;
  if (!fs.existsSync(MANIFEST_PATH)) {
    _cache = [];
    return _cache;
  }
  try {
    _cache = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8")) as BulkPage[];
  } catch {
    _cache = [];
  }
  return _cache;
}

// ─── Public helpers ───────────────────────────────────────────────────────────

export const BULK_PER_PAGE = 24;

/** All unique categories that appear in the manifest with their display info */
export function getBulkCategories(): BulkCategory[] {
  const pages = loadManifest();
  const counts: Record<string, number> = {};
  for (const p of pages) {
    counts[p.category] = (counts[p.category] ?? 0) + 1;
  }
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .map(([slug, count]) => {
      const meta = BULK_CATEGORY_META[slug] ?? { title: slug, icon: "🎨", color: "bg-gray-50" };
      return { slug, ...meta, count };
    });
}

/** Total number of bulk pages in a category */
export function getBulkPageCount(category: string): number {
  return loadManifest().filter((p) => p.category === category).length;
}

/** Paginated pages for a category (1-indexed page number) */
export function getBulkPagesByCategory(
  category: string,
  page = 1,
  perPage = BULK_PER_PAGE
): BulkPage[] {
  const all = loadManifest().filter((p) => p.category === category);
  const start = (page - 1) * perPage;
  return all.slice(start, start + perPage);
}

/** Find a single bulk page by its slug */
export function getBulkPageBySlug(slug: string): BulkPage | undefined {
  return loadManifest().find((p) => p.slug === slug);
}

/** Total pages across all categories */
export function getBulkTotal(): number {
  return loadManifest().length;
}

/** Category meta (title/icon/color) by slug */
export function getBulkCategoryMeta(slug: string) {
  return BULK_CATEGORY_META[slug] ?? { title: slug, icon: "🎨", color: "bg-gray-50" };
}
