#!/usr/bin/env node
/**
 * Pinterest bulk-upload CSV exporter for JiggyJoy.
 *
 * Walks the live sitemap, picks the top N URLs from each pinnable bucket
 * (coloring pages, games, worksheets), and emits a CSV that can be imported
 * into Pinterest's own bulk upload tool, Tailwind, Buffer, Later, or any
 * scheduler that accepts the de-facto standard column set:
 *
 *   Title, Pinterest board, Description, Link, Media URL
 *
 * Each row's `Media URL` points at JiggyJoy's existing /pin/* image route,
 * which renders a 1000×1500 Pinterest-optimized PNG on demand. No image files
 * to host, no S3, no Cloudinary — the pin images are generated by the same
 * Next.js process that serves the rest of the site.
 *
 * Usage:
 *   node scripts/pinterest-csv.mjs              # writes pinterest-pins.csv
 *   node scripts/pinterest-csv.mjs --out=foo.csv
 *   node scripts/pinterest-csv.mjs --limit-coloring=80 --limit-games=30
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const HOST = "https://www.jiggyjoy.com";
const SITEMAP_URL = `${HOST}/sitemap.xml`;

// ── CLI flags ────────────────────────────────────────────────────────────
const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const [k, v] = a.replace(/^--/, "").split("=");
    return [k, v ?? true];
  }),
);
const OUT_PATH = resolve(process.cwd(), args.out || "pinterest-pins.csv");
const LIMIT_COLORING = parseInt(args["limit-coloring"] ?? "50", 10);
const LIMIT_GAMES = parseInt(args["limit-games"] ?? "25", 10);
const LIMIT_WORKSHEETS = parseInt(args["limit-worksheets"] ?? "25", 10);

// ── Sitemap fetch (handles indexes too) ──────────────────────────────────
async function fetchSitemapEntries() {
  console.log(`→ Fetching sitemap from ${SITEMAP_URL}`);
  const xml = await (await fetch(SITEMAP_URL)).text();

  // Sitemap index? Recurse into children.
  const indexMatches = [
    ...xml.matchAll(/<sitemap>[\s\S]*?<loc>([^<]+)<\/loc>[\s\S]*?<\/sitemap>/g),
  ];
  if (indexMatches.length > 0) {
    console.log(`→ Sitemap index detected (${indexMatches.length} children)`);
    const all = [];
    for (const m of indexMatches) {
      const childXml = await (await fetch(m[1])).text();
      all.push(...parseUrlEntries(childXml));
    }
    return all;
  }
  return parseUrlEntries(xml);
}

function parseUrlEntries(xml) {
  // Match each <url>...</url> block, then pull <loc> and optional <priority>.
  const entries = [];
  for (const m of xml.matchAll(/<url>([\s\S]*?)<\/url>/g)) {
    const block = m[1];
    const loc = block.match(/<loc>([^<]+)<\/loc>/)?.[1];
    const priority = parseFloat(
      block.match(/<priority>([^<]+)<\/priority>/)?.[1] ?? "0.5",
    );
    if (loc) entries.push({ loc, priority });
  }
  return entries;
}

// ── Slug → human-readable title ──────────────────────────────────────────
function titleize(slug) {
  return slug
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .replace(/\bPdf\b/g, "PDF")
    .replace(/\bAbc\b/g, "ABC");
}

// Pinterest title cap = 100 chars. Truncate without breaking a word.
function clampTitle(s, max = 100) {
  if (s.length <= max) return s;
  const cut = s.slice(0, max);
  return cut.slice(0, cut.lastIndexOf(" ")).trim();
}

// ── Per-bucket pin builders ──────────────────────────────────────────────
function buildColoringPin(loc) {
  // /coloring-pages/<category>/<slug>
  const m = loc.match(/\/coloring-pages\/([^/]+)\/([^/?#]+)/);
  if (!m) return null;
  const [, category, slug] = m;
  const title = titleize(slug);
  return {
    title: clampTitle(`${title} — Free Printable`),
    board: "Free Coloring Pages",
    description: clampTitle(
      `Free printable ${title.toLowerCase()} — instant download, no signup, no watermark. Perfect for kids, classrooms and homeschool. Print as many copies as you need. #freecoloringpages #printables #kidsactivities #coloringpages #homeschool`,
      500,
    ),
    link: loc,
    media: `${HOST}/pin/coloring/${category}/${slug}`,
  };
}

function buildGamePin(loc) {
  // /games/<slug>  (skip /games/<topic-hub> like /games/math)
  const m = loc.match(/\/games\/([^/?#]+)$/);
  if (!m) return null;
  const slug = m[1];
  // Skip the hub topic pages (math, kindergarten, halloween, etc.)
  const HUBS = new Set([
    "math",
    "kindergarten",
    "halloween",
    "christmas",
    "easter",
    "3-year-olds",
    "4-year-olds",
    "5-year-olds",
  ]);
  if (HUBS.has(slug)) return null;
  const title = titleize(slug);
  return {
    title: clampTitle(`${title} — Free Online Game for Kids`),
    board: "Free Kids Games",
    description: clampTitle(
      `Play ${title} free online — no download, no signup, no ads aimed at kids. Educational browser game that works on phones, tablets and computers. #kidsgames #freegames #educationalgames #learningthroughplay #onlinegamesforkids`,
      500,
    ),
    link: loc,
    media: `${HOST}/pin/games/${slug}`,
  };
}

function buildWorksheetPin(loc) {
  // /worksheets/<slug>  (skip /worksheets/<grade-hub> and /worksheets/free/<topic>)
  const m = loc.match(/\/worksheets\/([^/?#]+)$/);
  if (!m) return null;
  const slug = m[1];
  if (loc.includes("/worksheets/free/")) return null;
  const HUBS = new Set([
    "preschool",
    "kindergarten",
    "math",
    "tracing",
    "alphabet",
  ]);
  if (HUBS.has(slug)) return null;
  const title = titleize(slug);
  return {
    title: clampTitle(`${title} — Free Printable PDF`),
    board: "Free Printable Worksheets",
    description: clampTitle(
      `Free printable ${title.toLowerCase()} — download and print instantly. Perfect for classrooms, homeschool and tutoring. No signup, no watermark, ready to use today. #freeworksheets #printables #homeschool #teachersofinstagram #worksheetsforkids`,
      500,
    ),
    link: loc,
    media: `${HOST}/pin/worksheets/${slug}`,
  };
}

// ── CSV escape ───────────────────────────────────────────────────────────
function csvCell(s) {
  if (s == null) return "";
  const needsQuote = /[",\n\r]/.test(s);
  const escaped = s.replace(/"/g, '""');
  return needsQuote ? `"${escaped}"` : escaped;
}

function toCsv(rows) {
  const header = ["Title", "Pinterest board", "Description", "Link", "Media URL"];
  const lines = [header.join(",")];
  for (const r of rows) {
    lines.push(
      [r.title, r.board, r.description, r.link, r.media].map(csvCell).join(","),
    );
  }
  return lines.join("\n") + "\n";
}

// ── Main ─────────────────────────────────────────────────────────────────
async function main() {
  const entries = await fetchSitemapEntries();
  console.log(`→ Found ${entries.length} sitemap entries`);

  // Sort by priority desc so higher-priority URLs are picked first.
  entries.sort((a, b) => b.priority - a.priority);

  const coloring = [];
  const games = [];
  const worksheets = [];

  for (const e of entries) {
    if (coloring.length < LIMIT_COLORING) {
      const pin = buildColoringPin(e.loc);
      if (pin) {
        coloring.push(pin);
        continue;
      }
    }
    if (games.length < LIMIT_GAMES) {
      const pin = buildGamePin(e.loc);
      if (pin) {
        games.push(pin);
        continue;
      }
    }
    if (worksheets.length < LIMIT_WORKSHEETS) {
      const pin = buildWorksheetPin(e.loc);
      if (pin) {
        worksheets.push(pin);
        continue;
      }
    }
  }

  const all = [...coloring, ...games, ...worksheets];
  const csv = toCsv(all);
  writeFileSync(OUT_PATH, csv, "utf8");

  console.log(`→ Coloring pins:   ${coloring.length} / ${LIMIT_COLORING}`);
  console.log(`→ Game pins:       ${games.length} / ${LIMIT_GAMES}`);
  console.log(`→ Worksheet pins:  ${worksheets.length} / ${LIMIT_WORKSHEETS}`);
  console.log(`→ Total rows:      ${all.length}`);
  console.log(`→ Wrote ${OUT_PATH}`);
  console.log("");
  console.log("Next step: upload pinterest-pins.csv to one of:");
  console.log("  • Pinterest Business → Bulk pin creation");
  console.log("  • Tailwind, Buffer, Later, Hootsuite (any scheduler)");
  console.log("Schedule ~10–25 pins/day per board to stay under spam thresholds.");
}

main().catch((err) => {
  console.error("✗ pinterest-csv failed:", err);
  process.exit(1);
});
